export interface Hose {
  id: string;
  patrim: string;
  num_mangueira: string;
  tipo: string;
  cap: string;
  prox_recarga: string;
  prox_teste: string;
  localizacao: string;
  ano_fab?: string;
  fabricante?: string;
  selo?: string;
  predio?: string;
  retiradoParaRecarga?: boolean;
  coberturaNoLocal?: boolean;
  checkLacre?: boolean;
  checkPressurizacao?: boolean;
  checkAnel?: boolean;
  checkPino?: boolean;
}

export const initialHoses: Hose[] = [
  {
    "id": "CD-P0-01-0",
    "patrim": "",
    "num_mangueira": "01",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-02-1",
    "patrim": "",
    "num_mangueira": "02",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-03-2",
    "patrim": "",
    "num_mangueira": "03",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-04-3",
    "patrim": "",
    "num_mangueira": "04",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-05-4",
    "patrim": "",
    "num_mangueira": "05",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-06-5",
    "patrim": "",
    "num_mangueira": "06",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-07-6",
    "patrim": "",
    "num_mangueira": "07",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-08-7",
    "patrim": "",
    "num_mangueira": "08",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-09-8",
    "patrim": "",
    "num_mangueira": "09",
    "tipo": "1",
    "cap": "40mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-10-9",
    "patrim": "",
    "num_mangueira": "10",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-11-10",
    "patrim": "",
    "num_mangueira": "11",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-12-11",
    "patrim": "",
    "num_mangueira": "12",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-13-12",
    "patrim": "",
    "num_mangueira": "13",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-14-13",
    "patrim": "",
    "num_mangueira": "14",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-15-14",
    "patrim": "",
    "num_mangueira": "15",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-16-15",
    "patrim": "",
    "num_mangueira": "16",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-17-16",
    "patrim": "",
    "num_mangueira": "17",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-18-17",
    "patrim": "",
    "num_mangueira": "18",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "CD-P0-19-18",
    "patrim": "",
    "num_mangueira": "19",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "CD"
  },
  {
    "id": "RAD-P0-01-0",
    "patrim": "",
    "num_mangueira": "01",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-02-1",
    "patrim": "",
    "num_mangueira": "02",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-03-2",
    "patrim": "",
    "num_mangueira": "03",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-04-3",
    "patrim": "",
    "num_mangueira": "04",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "07/10",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-05-4",
    "patrim": "",
    "num_mangueira": "05",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-06-5",
    "patrim": "",
    "num_mangueira": "06",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-07-6",
    "patrim": "",
    "num_mangueira": "07",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-08-7",
    "patrim": "",
    "num_mangueira": "08",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-09-8",
    "patrim": "",
    "num_mangueira": "09",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-10-9",
    "patrim": "",
    "num_mangueira": "10",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-11-10",
    "patrim": "",
    "num_mangueira": "11",
    "tipo": "1",
    "cap": "25mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/12",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-12-11",
    "patrim": "",
    "num_mangueira": "12",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "09/13",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-13-12",
    "patrim": "",
    "num_mangueira": "13",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "05/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-14-13",
    "patrim": "",
    "num_mangueira": "14",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-15-14",
    "patrim": "",
    "num_mangueira": "15",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-16-15",
    "patrim": "",
    "num_mangueira": "16",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "09/13",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-17-16",
    "patrim": "",
    "num_mangueira": "17",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-18-17",
    "patrim": "",
    "num_mangueira": "18",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "05/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-19-18",
    "patrim": "",
    "num_mangueira": "19",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "10/17",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-20-19",
    "patrim": "",
    "num_mangueira": "20",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "09/13",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-21-20",
    "patrim": "",
    "num_mangueira": "21",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "05/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P0-22-21",
    "patrim": "",
    "num_mangueira": "22",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "09/13",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-23-22",
    "patrim": "",
    "num_mangueira": "23",
    "tipo": "1",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "07/99",
    "fabricante": "PREDIAL",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-24-23",
    "patrim": "",
    "num_mangueira": "24",
    "tipo": "1",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "07/99",
    "fabricante": "PREDIAL",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-25-24",
    "patrim": "",
    "num_mangueira": "25",
    "tipo": "1",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "07/99",
    "fabricante": "PREDIAL",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-26-25",
    "patrim": "",
    "num_mangueira": "26",
    "tipo": "1",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "07/99",
    "fabricante": "PREDIAL",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-27-26",
    "patrim": "",
    "num_mangueira": "27",
    "tipo": "1",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "07/99",
    "fabricante": "PREDIAL",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-28-27",
    "patrim": "",
    "num_mangueira": "28",
    "tipo": "1",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "07/06",
    "fabricante": "PREDIAL",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-29-28",
    "patrim": "",
    "num_mangueira": "29",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/09",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-30-29",
    "patrim": "",
    "num_mangueira": "30",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/09",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-31-30",
    "patrim": "",
    "num_mangueira": "31",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "04/08",
    "fabricante": "KIDDE",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "RAD-P1-32-31",
    "patrim": "",
    "num_mangueira": "32",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "10/04",
    "fabricante": "POLI FLEX",
    "localizacao": "",
    "selo": "",
    "predio": "RAD"
  },
  {
    "id": "PA-P0-01-0",
    "patrim": "",
    "num_mangueira": "01",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "06/13",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-02-1",
    "patrim": "",
    "num_mangueira": "02",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "08/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-03-2",
    "patrim": "",
    "num_mangueira": "03",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "06/13",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-04-3",
    "patrim": "",
    "num_mangueira": "04",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "05/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-05-4",
    "patrim": "",
    "num_mangueira": "05",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "06/12",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-06-5",
    "patrim": "",
    "num_mangueira": "06",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "05/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-07-6",
    "patrim": "",
    "num_mangueira": "07",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "06/14",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-08-7",
    "patrim": "",
    "num_mangueira": "08",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "09/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-09-8",
    "patrim": "",
    "num_mangueira": "09",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-10-9",
    "patrim": "",
    "num_mangueira": "10",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "10/17",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-11-10",
    "patrim": "",
    "num_mangueira": "11",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "09/17",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-12-11",
    "patrim": "",
    "num_mangueira": "12",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "09/17",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-13-12",
    "patrim": "",
    "num_mangueira": "13",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "10/17",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-14-13",
    "patrim": "",
    "num_mangueira": "14",
    "tipo": "1",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "06/06",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-15-14",
    "patrim": "",
    "num_mangueira": "15",
    "tipo": "1",
    "cap": "40mm - 15m",
    "prox_recarga": "10/24",
    "prox_teste": "04/25",
    "ano_fab": "07/99",
    "fabricante": "PREDIAL",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-16-15",
    "patrim": "",
    "num_mangueira": "16",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-17-16",
    "patrim": "",
    "num_mangueira": "17",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-18-17",
    "patrim": "",
    "num_mangueira": "18",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-19-18",
    "patrim": "",
    "num_mangueira": "19",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-20-19",
    "patrim": "",
    "num_mangueira": "20",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-21-20",
    "patrim": "",
    "num_mangueira": "21",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P0-22-21",
    "patrim": "",
    "num_mangueira": "22",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-23-22",
    "patrim": "",
    "num_mangueira": "23",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-24-23",
    "patrim": "",
    "num_mangueira": "24",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-25-24",
    "patrim": "",
    "num_mangueira": "25",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-26-25",
    "patrim": "",
    "num_mangueira": "26",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "08/13",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-27-26",
    "patrim": "",
    "num_mangueira": "27",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "02/14",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-28-27",
    "patrim": "",
    "num_mangueira": "28",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "11/17",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-29-28",
    "patrim": "",
    "num_mangueira": "29",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-30-29",
    "patrim": "",
    "num_mangueira": "30",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-31-30",
    "patrim": "",
    "num_mangueira": "31",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-32-31",
    "patrim": "",
    "num_mangueira": "32",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-33-32",
    "patrim": "",
    "num_mangueira": "33",
    "tipo": "2",
    "cap": "40mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-34-33",
    "patrim": "",
    "num_mangueira": "34",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-35-34",
    "patrim": "",
    "num_mangueira": "35",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-36-35",
    "patrim": "",
    "num_mangueira": "36",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-37-36",
    "patrim": "",
    "num_mangueira": "37",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-38-37",
    "patrim": "",
    "num_mangueira": "38",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "INMASP",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-39-38",
    "patrim": "",
    "num_mangueira": "39",
    "tipo": "1",
    "cap": "25mm - 20m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "ARGUS",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-40-39",
    "patrim": "",
    "num_mangueira": "40",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-41-40",
    "patrim": "",
    "num_mangueira": "41",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-42-41",
    "patrim": "",
    "num_mangueira": "42",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-43-42",
    "patrim": "",
    "num_mangueira": "43",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-44-43",
    "patrim": "",
    "num_mangueira": "44",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P1-45-44",
    "patrim": "",
    "num_mangueira": "45",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-46-45",
    "patrim": "",
    "num_mangueira": "46",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-47-46",
    "patrim": "",
    "num_mangueira": "47",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "RESIL",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-48-47",
    "patrim": "",
    "num_mangueira": "48",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "RESIL",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-49-48",
    "patrim": "",
    "num_mangueira": "49",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-50-49",
    "patrim": "",
    "num_mangueira": "50",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "RESIL",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-51-50",
    "patrim": "",
    "num_mangueira": "51",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "RESIL",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-52-51",
    "patrim": "",
    "num_mangueira": "52",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "INMASP",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-53-52",
    "patrim": "",
    "num_mangueira": "53",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "INMASP",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-54-53",
    "patrim": "",
    "num_mangueira": "54",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "INMASP",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-55-54",
    "patrim": "",
    "num_mangueira": "55",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-56-55",
    "patrim": "",
    "num_mangueira": "56",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-57-56",
    "patrim": "",
    "num_mangueira": "57",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-58-57",
    "patrim": "",
    "num_mangueira": "58",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-59-58",
    "patrim": "",
    "num_mangueira": "59",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-60-59",
    "patrim": "",
    "num_mangueira": "60",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-61-60",
    "patrim": "",
    "num_mangueira": "61",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-62-61",
    "patrim": "",
    "num_mangueira": "62",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/20",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-63-62",
    "patrim": "",
    "num_mangueira": "63",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "RESIL",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-64-63",
    "patrim": "",
    "num_mangueira": "64",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "RESIL",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-65-64",
    "patrim": "",
    "num_mangueira": "65",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "RESIL",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-66-65",
    "patrim": "",
    "num_mangueira": "66",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "RESIL",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-67-66",
    "patrim": "",
    "num_mangueira": "67",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P2-68-67",
    "patrim": "",
    "num_mangueira": "68",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "03/19",
    "fabricante": "INMASP",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P3-69-68",
    "patrim": "",
    "num_mangueira": "69",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "05/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P3-70-69",
    "patrim": "",
    "num_mangueira": "70",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/13",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P3-71-70",
    "patrim": "",
    "num_mangueira": "71",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/13",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P3-72-71",
    "patrim": "",
    "num_mangueira": "72",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/12",
    "fabricante": "",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P3-73-72",
    "patrim": "",
    "num_mangueira": "73",
    "tipo": "2",
    "cap": "40mm - 15m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "05/12",
    "fabricante": "SUPERFLEX",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  },
  {
    "id": "PA-P3-74-73",
    "patrim": "",
    "num_mangueira": "74",
    "tipo": "1",
    "cap": "25mm - 30m",
    "prox_recarga": "11/24",
    "prox_teste": "05/25",
    "ano_fab": "06/13",
    "fabricante": "CM COUTO",
    "localizacao": "",
    "selo": "",
    "predio": "PA"
  }
];
