export interface EventData {
  id: string;
  date: string;
  time: string;
  building: 'CD' | 'RAD' | 'PA' | 'CDR' | 'CES' | string;
  floor: string;
  sector: string;
  reason: 'Bateria Baixa' | 'Equipamento Removido' | 'Fumaça' | 'Teste' | string;
  isFalseAlarm: boolean;
  attended: boolean;
  priority?: 'Baixa' | 'Média' | 'Alta' | 'Crítica';
  osStatus?: 'Aberta e Concluída' | 'Aberta e Não Concluída' | 'Não Aberta';
  numeroOS?: string;
  atendimentoFinal?: string;
  ht7?: string;
  ht9?: string;
  supervisao?: string;
  protocolo?: string;
  decisao?: string;
  atividade?: string;
  resultado?: string;
}

export interface AuditLog {
  id: string;
  action: 'CREATE' | 'UPDATE' | 'DELETE';
  eventId: string;
  eventDescription: string;
  timestamp: string;
  user: string;
}

// Dados baseados na 'NOVA PLANILHA DE EVENTOS'
export const eventsData: EventData[] = [
  { id: 'EV-001', date: '03/06/2026', time: '13h00', building: 'CD', floor: 'Sub.Solo 03', sector: 'Vest.Fem.', reason: 'Alarme Falso', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-002', date: '03/06/2026', time: '08h30', building: 'RAD', floor: '6º Andar', sector: 'C.infec2', reason: 'Fumaça/Outros', isFalseAlarm: false, attended: true, priority: 'Crítica' },
  { id: 'EV-003', date: '02/06/2026', time: '14h00', building: 'PA', floor: '9º Andar', sector: 'Quarto 916', reason: 'Nebulização', isFalseAlarm: true, attended: true, priority: 'Baixa' },
  { id: 'EV-004', date: '09/06/2026', time: '07h03', building: 'CD', floor: '10º Andar', sector: 'Hemodinamica', reason: 'Teste', isFalseAlarm: true, attended: true, priority: 'Baixa' },
  { id: 'EV-005', date: '12/01/2026', time: '17h16', building: 'PA', floor: '3º Andar', sector: 'Quarto 309', reason: 'Nebulização', isFalseAlarm: true, attended: true, priority: 'Baixa' },
  { id: 'EV-006', date: '12/01/2026', time: '09h02', building: 'PA', floor: '6º Andar', sector: 'Quarto 255', reason: 'Chuveiro', isFalseAlarm: true, attended: false, priority: 'Média' },
  { id: 'EV-007', date: '12/01/2026', time: '16h36', building: 'CD', floor: '1º Andar', sector: 'Elétrica 01', reason: 'Manutenção', isFalseAlarm: false, attended: true, priority: 'Alta' },
  { id: 'EV-008', date: '13/02/2026', time: '10h08', building: 'RAD', floor: '6º Andar', sector: 'Sl Ens 03', reason: 'Treinamento', isFalseAlarm: true, attended: true, priority: 'Baixa' },
  { id: 'EV-009', date: '12/01/2026', time: '04h30', building: 'PAD', floor: '4º Andar', sector: 'CTI cardio', reason: 'Alarme Falso', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-010', date: '19/01/2026', time: '17h08', building: 'CD', floor: '10º Andar', sector: 'SL. Reunião', reason: 'Outros', isFalseAlarm: false, attended: true, priority: 'Média' },
  { id: 'EV-011', date: '03/06/2026', time: '16h33', building: 'RAD', floor: 'Sub.Solo 01', sector: 'Radioterapia', reason: 'Manutenção', isFalseAlarm: false, attended: false, priority: 'Crítica' },
  { id: 'EV-012', date: '28/02/2026', time: '15h46', building: 'CD', floor: 'Sub.Solo 03', sector: 'Depósito', reason: 'Equip. Removido', isFalseAlarm: false, attended: true, priority: 'Baixa' },
  { id: 'EV-013', date: '18/02/2026', time: '06h25', building: 'PA', floor: '3º Andar', sector: 'Quarto 232', reason: 'Nebulização', isFalseAlarm: true, attended: true, priority: 'Baixa' },
  { id: 'EV-014', date: '02/02/2026', time: '11h09', building: 'PA', floor: '2º Andar', sector: 'Quarto 119', reason: 'Alarme Falso', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-015', date: '01/06/2026', time: '08h00', building: 'UPF', floor: 'Térreo', sector: 'Cons04', reason: 'Alarme Falso', isFalseAlarm: true, attended: true, priority: 'Baixa' },
  { id: 'EV-016', date: '12/01/2026', time: '09h08', building: 'PA', floor: '6º Andar', sector: 'Quarto 255', reason: 'Chuveiro', isFalseAlarm: true, attended: true, priority: 'Baixa' },
  { id: 'EV-017', date: '07/01/2026', time: '14h30', building: 'RAD', floor: '7º Andar', sector: 'GER. RH', reason: 'Outros', isFalseAlarm: false, attended: true, priority: 'Média' },
  { id: 'EV-018', date: '15/01/2026', time: '08h15', building: 'PA', floor: '5º Andar', sector: 'Bombas', reason: 'Manutenção', isFalseAlarm: false, attended: false, priority: 'Alta' },
  { id: 'EV-R001', date: '08/06/2026', time: '18h55', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R002', date: '08/06/2026', time: '19h25', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R003', date: '08/06/2026', time: '19h56', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R004', date: '08/06/2026', time: '20h26', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R005', date: '08/06/2026', time: '20h57', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R006', date: '08/06/2026', time: '21h27', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R007', date: '08/06/2026', time: '21h58', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R008', date: '08/06/2026', time: '22h28', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R009', date: '08/06/2026', time: '22h58', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R010', date: '09/06/2026', time: '00h30', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R011', date: '09/06/2026', time: '01h00', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R012', date: '09/06/2026', time: '01h31', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R013', date: '09/06/2026', time: '02h32', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R014', date: '09/06/2026', time: '03h02', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R015', date: '09/06/2026', time: '03h33', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R016', date: '09/06/2026', time: '04h03', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R017', date: '09/06/2026', time: '04h33', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R018', date: '09/06/2026', time: '05h04', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R019', date: '09/06/2026', time: '06h05', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R020', date: '09/06/2026', time: '06h35', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R021', date: '09/06/2026', time: '07h06', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R022', date: '09/06/2026', time: '07h36', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R023', date: '09/06/2026', time: '08h07', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R024', date: '09/06/2026', time: '08h37', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R025', date: '09/06/2026', time: '09h07', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R026', date: '09/06/2026', time: '09h38', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R027', date: '09/06/2026', time: '10h08', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R028', date: '09/06/2026', time: '10h39', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R029', date: '09/06/2026', time: '11h09', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R030', date: '09/06/2026', time: '11h40', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R031', date: '09/06/2026', time: '12h10', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R032', date: '09/06/2026', time: '12h41', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R033', date: '09/06/2026', time: '13h11', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R034', date: '09/06/2026', time: '13h42', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R035', date: '09/06/2026', time: '14h12', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R036', date: '09/06/2026', time: '14h43', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R037', date: '09/06/2026', time: '15h44', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R038', date: '09/06/2026', time: '15h53', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Equip. Removido', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R039', date: '03/06/2026', time: '05h17', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R040', date: '03/06/2026', time: '05h20', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R041', date: '03/06/2026', time: '05h44', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R042', date: '03/06/2026', time: '05h47', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R043', date: '03/06/2026', time: '05h49', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R044', date: '03/06/2026', time: '05h59', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R045', date: '03/06/2026', time: '06h14', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R046', date: '03/06/2026', time: '06h17', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R047', date: '03/06/2026', time: '06h18', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R048', date: '03/06/2026', time: '06h29', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R049', date: '03/06/2026', time: '06h44', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R050', date: '03/06/2026', time: '06h47', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R051', date: '03/06/2026', time: '06h47', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R052', date: '03/06/2026', time: '06h59', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R053', date: '03/06/2026', time: '07h14', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R054', date: '03/06/2026', time: '08h59', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R055', date: '03/06/2026', time: '09h12', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Equip. Removido', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R056', date: '03/06/2026', time: '09h15', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R057', date: '03/06/2026', time: '09h17', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Equip. Removido', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R058', date: '03/06/2026', time: '09h28', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Equip. Removido', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R059', date: '07/06/2026', time: '21h05', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R060', date: '07/06/2026', time: '21h36', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R061', date: '07/06/2026', time: '22h06', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R062', date: '07/06/2026', time: '22h37', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R063', date: '07/06/2026', time: '23h07', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R064', date: '08/06/2026', time: '00h08', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R065', date: '08/06/2026', time: '00h38', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R066', date: '08/06/2026', time: '01h39', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R067', date: '08/06/2026', time: '02h10', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R068', date: '08/06/2026', time: '02h40', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R069', date: '08/06/2026', time: '03h11', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R070', date: '08/06/2026', time: '03h41', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R071', date: '08/06/2026', time: '04h12', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R072', date: '08/06/2026', time: '04h42', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R073', date: '08/06/2026', time: '05h13', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R074', date: '08/06/2026', time: '05h43', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R075', date: '08/06/2026', time: '06h13', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R076', date: '08/06/2026', time: '06h44', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R077', date: '08/06/2026', time: '07h14', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R078', date: '08/06/2026', time: '07h45', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R079', date: '08/06/2026', time: '08h46', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R080', date: '08/06/2026', time: '10h17', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R081', date: '08/06/2026', time: '10h47', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R082', date: '08/06/2026', time: '11h18', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R083', date: '08/06/2026', time: '11h48', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R084', date: '08/06/2026', time: '12h19', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R085', date: '08/06/2026', time: '12h49', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R086', date: '08/06/2026', time: '13h20', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R087', date: '08/06/2026', time: '13h50', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R088', date: '08/06/2026', time: '14h21', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R089', date: '08/06/2026', time: '15h22', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R090', date: '08/06/2026', time: '15h52', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R091', date: '08/06/2026', time: '16h22', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R092', date: '08/06/2026', time: '16h53', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R093', date: '08/06/2026', time: '17h23', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R094', date: '08/06/2026', time: '17h54', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R095', date: '08/06/2026', time: '18h24', building: 'CD', floor: '3º Andar', sector: 'ONCOLOGIA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R096', date: '02/06/2026', time: '20h40', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R097', date: '02/06/2026', time: '20h48', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R098', date: '02/06/2026', time: '21h01', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R099', date: '02/06/2026', time: '21h09', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R100', date: '02/06/2026', time: '21h10', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R101', date: '02/06/2026', time: '21h17', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R102', date: '02/06/2026', time: '21h31', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R103', date: '02/06/2026', time: '21h38', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R104', date: '02/06/2026', time: '21h40', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R105', date: '02/06/2026', time: '21h47', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R106', date: '02/06/2026', time: '22h01', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R107', date: '02/06/2026', time: '22h10', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R108', date: '02/06/2026', time: '22h31', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R109', date: '02/06/2026', time: '22h36', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R110', date: '02/06/2026', time: '22h40', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R111', date: '02/06/2026', time: '23h01', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R112', date: '02/06/2026', time: '23h17', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R113', date: '02/06/2026', time: '23h30', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R114', date: '02/06/2026', time: '23h34', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R115', date: '02/06/2026', time: '23h41', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R116', date: '03/06/2026', time: '00h02', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R117', date: '03/06/2026', time: '00h11', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R118', date: '03/06/2026', time: '00h17', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R119', date: '03/06/2026', time: '00h30', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R120', date: '03/06/2026', time: '00h31', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R121', date: '03/06/2026', time: '00h41', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R122', date: '03/06/2026', time: '00h47', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R123', date: '03/06/2026', time: '01h00', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R124', date: '03/06/2026', time: '01h12', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R125', date: '03/06/2026', time: '01h17', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R126', date: '03/06/2026', time: '01h29', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R127', date: '03/06/2026', time: '01h30', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R128', date: '03/06/2026', time: '01h42', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R129', date: '03/06/2026', time: '01h58', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R130', date: '03/06/2026', time: '02h00', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R131', date: '03/06/2026', time: '02h12', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R132', date: '03/06/2026', time: '02h17', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R133', date: '03/06/2026', time: '02h27', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R134', date: '03/06/2026', time: '02h30', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R135', date: '03/06/2026', time: '02h42', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R136', date: '03/06/2026', time: '02h47', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R137', date: '03/06/2026', time: '03h00', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R138', date: '03/06/2026', time: '03h12', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R139', date: '03/06/2026', time: '03h17', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R140', date: '03/06/2026', time: '03h25', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R141', date: '03/06/2026', time: '03h30', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R142', date: '03/06/2026', time: '03h43', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R143', date: '03/06/2026', time: '03h47', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R144', date: '03/06/2026', time: '04h00', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R145', date: '03/06/2026', time: '04h13', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R146', date: '03/06/2026', time: '04h17', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R147', date: '03/06/2026', time: '04h23', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R148', date: '03/06/2026', time: '04h30', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R149', date: '03/06/2026', time: '04h43', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R150', date: '03/06/2026', time: '04h47', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R151', date: '03/06/2026', time: '04h51', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R152', date: '03/06/2026', time: '05h13', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R153', date: '02/06/2026', time: '11h03', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R154', date: '02/06/2026', time: '11h33', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R155', date: '02/06/2026', time: '11h35', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R156', date: '02/06/2026', time: '12h00', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R157', date: '02/06/2026', time: '12h02', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R158', date: '02/06/2026', time: '12h05', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R159', date: '02/06/2026', time: '12h29', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R160', date: '02/06/2026', time: '12h36', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R161', date: '02/06/2026', time: '12h48', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R162', date: '02/06/2026', time: '13h02', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R163', date: '02/06/2026', time: '13h06', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R164', date: '02/06/2026', time: '13h36', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R165', date: '02/06/2026', time: '13h48', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R166', date: '02/06/2026', time: '13h55', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R167', date: '02/06/2026', time: '14h02', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R168', date: '02/06/2026', time: '14h06', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R169', date: '02/06/2026', time: '14h18', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R170', date: '02/06/2026', time: '14h32', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R171', date: '02/06/2026', time: '14h37', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R172', date: '02/06/2026', time: '14h53', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R173', date: '02/06/2026', time: '15h02', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R174', date: '02/06/2026', time: '15h07', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R175', date: '02/06/2026', time: '15h18', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R176', date: '02/06/2026', time: '15h22', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R177', date: '02/06/2026', time: '15h32', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R178', date: '02/06/2026', time: '15h37', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R179', date: '02/06/2026', time: '15h51', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R180', date: '02/06/2026', time: '16h02', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R181', date: '02/06/2026', time: '16h07', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R182', date: '02/06/2026', time: '16h18', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R183', date: '02/06/2026', time: '16h20', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R184', date: '02/06/2026', time: '16h32', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R185', date: '02/06/2026', time: '16h38', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R186', date: '02/06/2026', time: '16h49', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R187', date: '02/06/2026', time: '17h02', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R188', date: '02/06/2026', time: '17h08', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R189', date: '02/06/2026', time: '17h18', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R190', date: '02/06/2026', time: '17h38', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R191', date: '02/06/2026', time: '17h48', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R192', date: '02/06/2026', time: '18h02', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R193', date: '02/06/2026', time: '18h08', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R194', date: '02/06/2026', time: '18h18', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R195', date: '02/06/2026', time: '18h38', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R196', date: '02/06/2026', time: '18h45', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R197', date: '02/06/2026', time: '18h48', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R198', date: '02/06/2026', time: '19h09', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R199', date: '02/06/2026', time: '19h18', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R200', date: '02/06/2026', time: '19h31', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R201', date: '02/06/2026', time: '19h39', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R202', date: '02/06/2026', time: '19h42', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R203', date: '02/06/2026', time: '19h48', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R204', date: '02/06/2026', time: '20h01', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R205', date: '02/06/2026', time: '20h09', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R206', date: '02/06/2026', time: '20h11', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R207', date: '02/06/2026', time: '20h18', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R208', date: '02/06/2026', time: '20h31', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R209', date: '02/06/2026', time: '20h39', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R210', date: '29/05/2026', time: '10h19', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R211', date: '29/05/2026', time: '10h49', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R212', date: '29/05/2026', time: '10h56', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R213', date: '29/05/2026', time: '11h11', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R214', date: '29/05/2026', time: '11h20', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R215', date: '29/05/2026', time: '11h26', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R216', date: '29/05/2026', time: '11h40', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R217', date: '29/05/2026', time: '11h50', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R218', date: '29/05/2026', time: '11h56', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R219', date: '29/05/2026', time: '12h09', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R220', date: '29/05/2026', time: '12h20', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R221', date: '29/05/2026', time: '12h50', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R222', date: '29/05/2026', time: '12h56', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R223', date: '29/05/2026', time: '13h07', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R224', date: '29/05/2026', time: '13h21', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R225', date: '29/05/2026', time: '13h26', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R226', date: '29/05/2026', time: '13h36', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R227', date: '29/05/2026', time: '13h51', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R228', date: '29/05/2026', time: '13h56', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R229', date: '29/05/2026', time: '14h05', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R230', date: '29/05/2026', time: '14h51', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R231', date: '29/05/2026', time: '14h56', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R232', date: '29/05/2026', time: '15h02', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R233', date: '29/05/2026', time: '15h22', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R234', date: '29/05/2026', time: '15h26', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R235', date: '29/05/2026', time: '15h31', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R236', date: '29/05/2026', time: '15h52', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R237', date: '02/06/2026', time: '09h04', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R238', date: '02/06/2026', time: '09h48', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R239', date: '02/06/2026', time: '10h03', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R240', date: '02/06/2026', time: '10h04', building: 'PA', floor: '10º Andar', sector: 'BOX 02', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R241', date: '02/06/2026', time: '10h33', building: 'CD', floor: 'Sub.Solo', sector: 'DMI', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R242', date: '02/06/2026', time: '10h33', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R243', date: '02/06/2026', time: '10h48', building: 'CD', floor: 'Sub.Solo', sector: 'ARM.INTERNA', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
  { id: 'EV-R244', date: '02/06/2026', time: '11h02', building: 'RAD', floor: 'Sub.Solo', sector: 'ARQUIVO RAIOX', reason: 'Bateria Baixa', isFalseAlarm: true, attended: false, priority: 'Baixa' },
];

export interface AppSettings {
  buildings: string[];
  reasons: string[];
  osStatuses: string[];
  priorities: string[];
  extinguisherTypes: string[];
  amplifierStatuses: string[];
}

export const defaultSettings: AppSettings = {
  buildings: ['CD', 'RAD', 'PA', 'CDR', 'CES'],
  reasons: ['Bateria Baixa', 'Equipamento Removido', 'Fumaça', 'Teste'],
  osStatuses: ['Aberta e Concluída', 'Aberta e Não Concluída', 'Não Aberta'],
  priorities: ['Baixa', 'Média', 'Alta', 'Crítica'],
  extinguisherTypes: ['ABC', 'CO2', 'AP', 'BC'],
  amplifierStatuses: ['Online / Sincronizado', 'Offline', 'Erro']
};
